//! This file is auto-generated by build.rs. DO NOT EDIT.
//! Contains database table models.

use serde::{Deserialize, Serialize};
use ts_rs::TS;
use chrono::{NaiveDate, DateTime, Utc};
use super::types::*;

#[derive(Debug, Serialize, sqlx::FromRow, TS)]
#[ts(export)]
pub struct Kanwil {
    pub id: i32,
    pub nama_kanwil: String,
    pub alamat_kanwil: Option<String>,
    pub nomor_telepon_kanwil: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deleted_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Serialize, sqlx::FromRow, TS)]
#[ts(export)]
pub struct Bapas {
    pub id: i32,
    pub kanwil_id: i32,
    pub nama_bapas: String,
    pub kota_bapas: String,
    pub alamat_bapas: Option<String>,
    pub nomor_telepon_bapas: Option<String>,
    pub email_bapas: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub deleted_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Serialize, sqlx::FromRow, TS)]
#[ts(export)]
pub struct Users {
    pub id: i32,
    pub nip: String,
    pub nama: String,
    pub gelar_depan: Option<String>,
    pub gelar_belakang: Option<String>,
    pub pangkat_golongan: Option<String>,
    pub jabatan: Option<String>,
    pub unit_kerja_id: Option<i32>,
    pub kanwil_id: Option<i32>,
    pub status_kepegawaian: UserStatusKepegawaian,
    pub email: Option<String>,
    pub nomor_telepon: Option<String>,
    pub status_aktif: UserStatusAktif,
    pub role: UserRole,
    #[serde(skip_serializing)]
    pub password_hash: String,
    pub deleted_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Serialize, sqlx::FromRow, TS)]
#[ts(export)]
pub struct Klien {
    pub id: i32,
    pub tipe: TipeKlien,
    pub nama: String,
    pub alamat: Option<String>,
    pub tempat_lahir: Option<String>,
    pub tanggal_lahir: Option<NaiveDate>,
    pub jenis_kelamin: Option<JenisKelaminEnum>,
    pub agama: Option<String>,
    pub pekerjaan: Option<JenisPekerjaan>,
    pub pendidikan_terakhir: Option<TingkatPendidikan>,
    pub bapas_id: i32,
    pub pk_id: i32,
    pub kanwil_id: Option<i32>,
    pub online_akses: bool,
    pub pengulangan: bool,
    pub kewarganegaraan: Option<KewarganegaraanEnum>,
    pub negara_asal: Option<String>,
    pub suku: Option<String>,
    pub keterangan: Option<String>,
    pub catatan: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub created_by: Option<i32>,
    pub updated_by: Option<i32>,
    pub deleted_at: Option<DateTime<Utc>>,
}

#[derive(TS)]
#[ts(export_to = "../../frontend/src/lib/types/backend.d.ts")]
pub enum AllModelTypes {}
