//! This file is auto-generated by build.rs. DO NOT EDIT.
//! Contains database ENUM type definitions.

use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, sqlx::Type, TS)]
#[sqlx(type_name = "jenis_pekerjaan")]
#[ts(export)]
pub enum JenisPekerjaan {
    #[sqlx(rename = "BELUM/TIDAK BEKERJA")] #[serde(rename = "BELUM/TIDAK BEKERJA")]
    BelumTidakBekerja,
    #[sqlx(rename = "PEGAWAI NEGERI SIPIL")] #[serde(rename = "PEGAWAI NEGERI SIPIL")]
    PegawaiNegeriSipil,
    #[sqlx(rename = "TENTARA NASIONAL INDONESIA")] #[serde(rename = "TENTARA NASIONAL INDONESIA")]
    TentaraNasionalIndonesia,
    #[sqlx(rename = "KEPOLISIAN RI")] #[serde(rename = "KEPOLISIAN RI")]
    KepolisianRi,
    #[sqlx(rename = "KARYAWAN BUMN")] #[serde(rename = "KARYAWAN BUMN")]
    KaryawanBumn,
    #[sqlx(rename = "KARYAWAN BUMD")] #[serde(rename = "KARYAWAN BUMD")]
    KaryawanBumd,
    #[sqlx(rename = "ANGGOTA DPR-RI")] #[serde(rename = "ANGGOTA DPR-RI")]
    AnggotaDprRi,
    #[sqlx(rename = "ANGGOTA DPD")] #[serde(rename = "ANGGOTA DPD")]
    AnggotaDpd,
    #[sqlx(rename = "ANGGOTA BPK")] #[serde(rename = "ANGGOTA BPK")]
    AnggotaBpk,
    #[sqlx(rename = "PRESIDEN")] #[serde(rename = "PRESIDEN")]
    Presiden,
    #[sqlx(rename = "WAKIL PRESIDEN")] #[serde(rename = "WAKIL PRESIDEN")]
    WakilPresiden,
    #[sqlx(rename = "ANGGOTA MAHKAMAH KONSTITUSI")] #[serde(rename = "ANGGOTA MAHKAMAH KONSTITUSI")]
    AnggotaMahkamahKonstitusi,
    #[sqlx(rename = "ANGGOTA KABINET/KEMENTERIAN")] #[serde(rename = "ANGGOTA KABINET/KEMENTERIAN")]
    AnggotaKabinetKementerian,
    #[sqlx(rename = "DUTA BESAR")] #[serde(rename = "DUTA BESAR")]
    DutaBesar,
    #[sqlx(rename = "GUBERNUR")] #[serde(rename = "GUBERNUR")]
    Gubernur,
    #[sqlx(rename = "WAKIL GUBERNUR")] #[serde(rename = "WAKIL GUBERNUR")]
    WakilGubernur,
    #[sqlx(rename = "BUPATI")] #[serde(rename = "BUPATI")]
    Bupati,
    #[sqlx(rename = "WAKIL BUPATI")] #[serde(rename = "WAKIL BUPATI")]
    WakilBupati,
    #[sqlx(rename = "WALIKOTA")] #[serde(rename = "WALIKOTA")]
    Walikota,
    #[sqlx(rename = "WAKIL WALIKOTA")] #[serde(rename = "WAKIL WALIKOTA")]
    WakilWalikota,
    #[sqlx(rename = "ANGGOTA DPRD PROVINSI")] #[serde(rename = "ANGGOTA DPRD PROVINSI")]
    AnggotaDprdProvinsi,
    #[sqlx(rename = "ANGGOTA DPRD KABUPATEN/KOTA")] #[serde(rename = "ANGGOTA DPRD KABUPATEN/KOTA")]
    AnggotaDprdKabupatenKota,
    #[sqlx(rename = "PENGACARA")] #[serde(rename = "PENGACARA")]
    Pengacara,
    #[sqlx(rename = "NOTARIS")] #[serde(rename = "NOTARIS")]
    Notaris,
    #[sqlx(rename = "PENELITI")] #[serde(rename = "PENELITI")]
    Peneliti,
    #[sqlx(rename = "PERANGKAT DESA")] #[serde(rename = "PERANGKAT DESA")]
    PerangkatDesa,
    #[sqlx(rename = "KEPALA DESA")] #[serde(rename = "KEPALA DESA")]
    KepalaDesa,
    #[sqlx(rename = "DOSEN")] #[serde(rename = "DOSEN")]
    Dosen,
    #[sqlx(rename = "GURU")] #[serde(rename = "GURU")]
    Guru,
    #[sqlx(rename = "PERDAGANGAN")] #[serde(rename = "PERDAGANGAN")]
    Perdagangan,
    #[sqlx(rename = "INDUSTRI")] #[serde(rename = "INDUSTRI")]
    Industri,
    #[sqlx(rename = "KONSTRUKSI")] #[serde(rename = "KONSTRUKSI")]
    Konstruksi,
    #[sqlx(rename = "TRANSPORTASI")] #[serde(rename = "TRANSPORTASI")]
    Transportasi,
    #[sqlx(rename = "KARYAWAN SWASTA")] #[serde(rename = "KARYAWAN SWASTA")]
    KaryawanSwasta,
    #[sqlx(rename = "KARYAWAN HONORER")] #[serde(rename = "KARYAWAN HONORER")]
    KaryawanHonorer,
    #[sqlx(rename = "BURUH HARIAN LEPAS")] #[serde(rename = "BURUH HARIAN LEPAS")]
    BuruhHarianLepas,
    #[sqlx(rename = "PEMBANTU RUMAH TANGGA")] #[serde(rename = "PEMBANTU RUMAH TANGGA")]
    PembantuRumahTangga,
    #[sqlx(rename = "TUKANG CUKUR")] #[serde(rename = "TUKANG CUKUR")]
    TukangCukur,
    #[sqlx(rename = "TUKANG LISTRIK")] #[serde(rename = "TUKANG LISTRIK")]
    TukangListrik,
    #[sqlx(rename = "TUKANG BATU")] #[serde(rename = "TUKANG BATU")]
    TukangBatu,
    #[sqlx(rename = "TUKANG KAYU")] #[serde(rename = "TUKANG KAYU")]
    TukangKayu,
    #[sqlx(rename = "TUKANG SOL SEPATU")] #[serde(rename = "TUKANG SOL SEPATU")]
    TukangSolSepatu,
    #[sqlx(rename = "TUKANG LAS/PANDAI BESI")] #[serde(rename = "TUKANG LAS/PANDAI BESI")]
    TukangLasPandaiBesi,
    #[sqlx(rename = "TUKANG JAHIT")] #[serde(rename = "TUKANG JAHIT")]
    TukangJahit,
    #[sqlx(rename = "TUKANG GIGI")] #[serde(rename = "TUKANG GIGI")]
    TukangGigi,
    #[sqlx(rename = "PENATA RIAS")] #[serde(rename = "PENATA RIAS")]
    PenataRias,
    #[sqlx(rename = "PENATA BUSANA")] #[serde(rename = "PENATA BUSANA")]
    PenataBusana,
    #[sqlx(rename = "PENATA RAMBUT")] #[serde(rename = "PENATA RAMBUT")]
    PenataRambut,
    #[sqlx(rename = "MEKANIK")] #[serde(rename = "MEKANIK")]
    Mekanik,
    #[sqlx(rename = "SENIMAN")] #[serde(rename = "SENIMAN")]
    Seniman,
    #[sqlx(rename = "TABIB")] #[serde(rename = "TABIB")]
    Tabib,
    #[sqlx(rename = "PARAJI")] #[serde(rename = "PARAJI")]
    Paraji,
    #[sqlx(rename = "PERANCANG BUSANA")] #[serde(rename = "PERANCANG BUSANA")]
    PerancangBusana,
    #[sqlx(rename = "PENTERJEMAH")] #[serde(rename = "PENTERJEMAH")]
    Penterjemah,
    #[sqlx(rename = "WARTAWAN")] #[serde(rename = "WARTAWAN")]
    Wartawan,
    #[sqlx(rename = "JURU MASAK")] #[serde(rename = "JURU MASAK")]
    JuruMasak,
    #[sqlx(rename = "PROMOTOR ACARA")] #[serde(rename = "PROMOTOR ACARA")]
    PromotorAcara,
    #[sqlx(rename = "PILOT")] #[serde(rename = "PILOT")]
    Pilot,
    #[sqlx(rename = "ARSITEK")] #[serde(rename = "ARSITEK")]
    Arsitek,
    #[sqlx(rename = "AKUNTAN")] #[serde(rename = "AKUNTAN")]
    Akuntan,
    #[sqlx(rename = "KONSULTAN")] #[serde(rename = "KONSULTAN")]
    Konsultan,
    #[sqlx(rename = "PENYIAR TELEVISI")] #[serde(rename = "PENYIAR TELEVISI")]
    PenyiarTelevisi,
    #[sqlx(rename = "PENYIAR RADIO")] #[serde(rename = "PENYIAR RADIO")]
    PenyiarRadio,
    #[sqlx(rename = "PELAUT")] #[serde(rename = "PELAUT")]
    Pelaut,
    #[sqlx(rename = "SOPIR")] #[serde(rename = "SOPIR")]
    Sopir,
    #[sqlx(rename = "PIALANG")] #[serde(rename = "PIALANG")]
    Pialang,
    #[sqlx(rename = "PARANORMAL")] #[serde(rename = "PARANORMAL")]
    Paranormal,
    #[sqlx(rename = "PEDAGANG")] #[serde(rename = "PEDAGANG")]
    Pedagang,
    #[sqlx(rename = "WIRASWASTA")] #[serde(rename = "WIRASWASTA")]
    Wiraswasta,
    #[sqlx(rename = "PETANI/PEKEBUN")] #[serde(rename = "PETANI/PEKEBUN")]
    PetaniPekebun,
    #[sqlx(rename = "PETERNAK")] #[serde(rename = "PETERNAK")]
    Peternak,
    #[sqlx(rename = "BURUH TANI/PERKEBUNAN")] #[serde(rename = "BURUH TANI/PERKEBUNAN")]
    BuruhTaniPerkebunan,
    #[sqlx(rename = "BURUH PETERNAKAN")] #[serde(rename = "BURUH PETERNAKAN")]
    BuruhPeternakan,
    #[sqlx(rename = "NELAYAN/PERIKANAN")] #[serde(rename = "NELAYAN/PERIKANAN")]
    NelayanPerikanan,
    #[sqlx(rename = "BURUH NELAYAN/PERIKANAN")] #[serde(rename = "BURUH NELAYAN/PERIKANAN")]
    BuruhNelayanPerikanan,
    #[sqlx(rename = "IMAM MESJID")] #[serde(rename = "IMAM MESJID")]
    ImamMesjid,
    #[sqlx(rename = "PENDETA")] #[serde(rename = "PENDETA")]
    Pendeta,
    #[sqlx(rename = "PASTOR")] #[serde(rename = "PASTOR")]
    Pastor,
    #[sqlx(rename = "USTADZ/MUBALIGH")] #[serde(rename = "USTADZ/MUBALIGH")]
    UstadzMubaligh,
    #[sqlx(rename = "BIARAWATI")] #[serde(rename = "BIARAWATI")]
    Biarawati,
    #[sqlx(rename = "PELAJAR/MAHASISWA")] #[serde(rename = "PELAJAR/MAHASISWA")]
    PelajarMahasiswa,
    #[sqlx(rename = "DOKTER")] #[serde(rename = "DOKTER")]
    Dokter,
    #[sqlx(rename = "BIDAN")] #[serde(rename = "BIDAN")]
    Bidan,
    #[sqlx(rename = "PERAWAT")] #[serde(rename = "PERAWAT")]
    Perawat,
    #[sqlx(rename = "APOTEKER")] #[serde(rename = "APOTEKER")]
    Apoteker,
    #[sqlx(rename = "PSIKIATER/PSIKOLOG")] #[serde(rename = "PSIKIATER/PSIKOLOG")]
    PsikiaterPsikolog,
    #[sqlx(rename = "PENSIUNAN")] #[serde(rename = "PENSIUNAN")]
    Pensiunan,
    #[sqlx(rename = "MENGURUS RUMAH TANGGA")] #[serde(rename = "MENGURUS RUMAH TANGGA")]
    MengurusRumahTangga,
    #[sqlx(rename = "LAINNYA")] #[serde(rename = "LAINNYA")]
    Lainnya,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, sqlx::Type, TS)]
#[sqlx(type_name = "kewarganegaraan_enum")]
#[ts(export)]
pub enum KewarganegaraanEnum {
    #[sqlx(rename = "WNI")] #[serde(rename = "WNI")]
    Wni,
    #[sqlx(rename = "WNA")] #[serde(rename = "WNA")]
    Wna,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, sqlx::Type, TS)]
#[sqlx(type_name = "metode_lapor_enum")]
#[ts(export)]
pub enum MetodeLaporEnum {
    Mandiri,
    MandiriDiKantor,
    Petugas,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, sqlx::Type, TS)]
#[sqlx(type_name = "nama_instansi")]
#[ts(export)]
pub enum NamaInstansi {
    #[sqlx(rename = "Lembaga Pemasyarakatan")] #[serde(rename = "Lembaga Pemasyarakatan")]
    LembagaPemasyarakatan,
    #[sqlx(rename = "Rumah Tahanan Negara")] #[serde(rename = "Rumah Tahanan Negara")]
    RumahTahananNegara,
    #[sqlx(rename = "Balai Pemasyarakatan")] #[serde(rename = "Balai Pemasyarakatan")]
    BalaiPemasyarakatan,
    #[sqlx(rename = "Kejaksaan Negeri")] #[serde(rename = "Kejaksaan Negeri")]
    KejaksaanNegeri,
    #[sqlx(rename = "Pengadilan Negeri")] #[serde(rename = "Pengadilan Negeri")]
    PengadilanNegeri,
    #[sqlx(rename = "Kepolisian Resor")] #[serde(rename = "Kepolisian Resor")]
    KepolisianResor,
    #[sqlx(rename = "Kepolisian Sektor")] #[serde(rename = "Kepolisian Sektor")]
    KepolisianSektor,
    #[sqlx(rename = "Kepolisian Daerah")] #[serde(rename = "Kepolisian Daerah")]
    KepolisianDaerah,
    #[sqlx(rename = "Kepolisian Republik Indonesia")] #[serde(rename = "Kepolisian Republik Indonesia")]
    KepolisianRepublikIndonesia,
    #[sqlx(rename = "Pengadilan Tinggi")] #[serde(rename = "Pengadilan Tinggi")]
    PengadilanTinggi,
    #[sqlx(rename = "Mahkamah Agung")] #[serde(rename = "Mahkamah Agung")]
    MahkamahAgung,
    Lainnya,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, sqlx::Type, TS)]
#[sqlx(type_name = "tingkat_pendidikan")]
#[ts(export)]
pub enum TingkatPendidikan {
    #[sqlx(rename = "Tidak Sekolah")] #[serde(rename = "Tidak Sekolah")]
    TidakSekolah,
    #[sqlx(rename = "SD Tidak Lulus")] #[serde(rename = "SD Tidak Lulus")]
    SdTidakLulus,
    #[sqlx(rename = "SD atau Sederajat")] #[serde(rename = "SD atau Sederajat")]
    SdAtauSederajat,
    #[sqlx(rename = "SMP atau Sederajat")] #[serde(rename = "SMP atau Sederajat")]
    SmpAtauSederajat,
    #[sqlx(rename = "SMA atau Sederajat")] #[serde(rename = "SMA atau Sederajat")]
    SmaAtauSederajat,
    #[sqlx(rename = "D1 atau Sederajat")] #[serde(rename = "D1 atau Sederajat")]
    D1AtauSederajat,
    #[sqlx(rename = "D2 atau Sederajat")] #[serde(rename = "D2 atau Sederajat")]
    D2AtauSederajat,
    #[sqlx(rename = "D3 atau Sederajat")] #[serde(rename = "D3 atau Sederajat")]
    D3AtauSederajat,
    #[sqlx(rename = "S1 atau Sederajat")] #[serde(rename = "S1 atau Sederajat")]
    S1AtauSederajat,
    #[sqlx(rename = "S2 atau Sederajat")] #[serde(rename = "S2 atau Sederajat")]
    S2AtauSederajat,
    #[sqlx(rename = "S3 atau Sederajat")] #[serde(rename = "S3 atau Sederajat")]
    S3AtauSederajat,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, sqlx::Type, TS)]
#[sqlx(type_name = "tipe_klien")]
#[ts(export)]
pub enum TipeKlien {
    Dewasa,
    Anak,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, sqlx::Type, TS)]
#[sqlx(type_name = "user_role")]
#[ts(export)]
pub enum UserRole {
    Pegawai,
    AdminBapas,
    AdminKanwil,
    SuperAdmin,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, sqlx::Type, TS)]
#[sqlx(type_name = "user_status_aktif")]
#[ts(export)]
pub enum UserStatusAktif {
    Aktif,
    Deaktif,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq, sqlx::Type, TS)]
#[sqlx(type_name = "user_status_kepegawaian")]
#[ts(export)]
pub enum UserStatusKepegawaian {
    Aktif,
    PindahJabatan,
    Pensiun,
    Lainya,
}

#[derive(TS)]
#[ts(export_to = "../../frontend/src/lib/types/backend.d.ts")]
pub enum AllEnumTypes {}
