// AUTO-GENERATED FILE FROM DB ENUMS

export enum JenisKelaminEnum {
    LakiLaki = "Laki-laki",
    Perempuan = "Perempuan",
}

export enum JenisPekerjaanEnum {
    BelumTidakBekerja = "Belum/Tidak Bekerja",
    PegawaiNegeriSipil = "Pegawai Negeri Sipil",
    TentaraNasionalIndonesia = "Tentara Nasional Indonesia",
    KepolisianRI = "Kepolisian RI",
    KaryawanBUMN = "Karyawan BUMN",
    KaryawanBUMD = "Karyawan BUMD",
    AnggotaDPRRI = "Anggota DPR-RI",
    AnggotaDPD = "Anggota DPD",
    AnggotaBPK = "Anggota BPK",
    Presiden = "Presiden",
    WakilPresiden = "Wakil Presiden",
    AnggotaMahkamahKonstitusi = "Anggota Mahkamah Konstitusi",
    AnggotaKabinetKementerian = "Anggota Kabinet/Kementerian",
    DutaBesar = "Duta Besar",
    Gubernur = "Gubernur",
    WakilGubernur = "Wakil Gubernur",
    Bupati = "Bupati",
    WakilBupati = "Wakil Bupati",
    Walikota = "Walikota",
    WakilWalikota = "Wakil Walikota",
    AnggotaDPRDProvinsi = "Anggota DPRD Provinsi",
    AnggotaDPRDKabupatenKota = "Anggota DPRD Kabupaten/Kota",
    Pengacara = "Pengacara",
    Notaris = "Notaris",
    Peneliti = "Peneliti",
    PerangkatDesa = "Perangkat Desa",
    KepalaDesa = "Kepala Desa",
    Dosen = "Dosen",
    Guru = "Guru",
    Perdagangan = "Perdagangan",
    Industri = "Industri",
    Konstruksi = "Konstruksi",
    Transportasi = "Transportasi",
    KaryawanSwasta = "Karyawan Swasta",
    KaryawanHonorer = "Karyawan Honorer",
    BuruhHarianLepas = "Buruh Harian Lepas",
    PembantuRumahTangga = "Pembantu Rumah Tangga",
    TukangCukur = "Tukang Cukur",
    TukangListrik = "Tukang Listrik",
    TukangBatu = "Tukang Batu",
    TukangKayu = "Tukang Kayu",
    TukangSolSepatu = "Tukang Sol Sepatu",
    TukangLasPandaiBesi = "Tukang Las/Pandai Besi",
    TukangJahit = "Tukang Jahit",
    TukangGigi = "Tukang Gigi",
    PenataRias = "Penata Rias",
    PenataBusana = "Penata Busana",
    PenataRambut = "Penata Rambut",
    Mekanik = "Mekanik",
    Seniman = "Seniman",
    Tabib = "Tabib",
    Paraji = "Paraji",
    PerancangBusana = "Perancang Busana",
    Penterjemah = "Penterjemah",
    Wartawan = "Wartawan",
    JuruMasak = "Juru Masak",
    PromotorAcara = "Promotor Acara",
    Pilot = "Pilot",
    Arsitek = "Arsitek",
    Akuntan = "Akuntan",
    Konsultan = "Konsultan",
    PenyiarTelevisi = "Penyiar Televisi",
    PenyiarRadio = "Penyiar Radio",
    Pelaut = "Pelaut",
    Sopir = "Sopir",
    Pialang = "Pialang",
    Paranormal = "Paranormal",
    Pedagang = "Pedagang",
    Wiraswasta = "Wiraswasta",
    PetaniPekebun = "Petani/Pekebun",
    Peternak = "Peternak",
    BuruhTaniPerkebunan = "Buruh Tani/Perkebunan",
    BuruhPeternakan = "Buruh Peternakan",
    NelayanPerikanan = "Nelayan/Perikanan",
    BuruhNelayanPerikanan = "Buruh Nelayan/Perikanan",
    ImamMesjid = "Imam Mesjid",
    Pendeta = "Pendeta",
    Pastor = "Pastor",
    UstadzMubaligh = "Ustadz/Mubaligh",
    Biarawati = "Biarawati",
    PelajarMahasiswa = "Pelajar/Mahasiswa",
    Dokter = "Dokter",
    Bidan = "Bidan",
    Perawat = "Perawat",
    Apoteker = "Apoteker",
    PsikiaterPsikolog = "Psikiater/Psikolog",
    Pensiunan = "Pensiunan",
    MengurusRumahTangga = "Mengurus Rumah Tangga",
    Lainnya = "Lainnya",
}

export enum KewarganegaraanEnum {
    WNI = "WNI",
    WNA = "WNA",
}

export enum MetodeLaporEnum {
    Online = "Online",
    SelfService = "Self-Service",
    Petugas = "Petugas",
}

export enum NamaInstansiEnum {
    LembagaPemasyarakatan = "Lembaga Pemasyarakatan",
    RumahTahananNegara = "Rumah Tahanan Negara",
    BalaiPemasyarakatan = "Balai Pemasyarakatan",
    KejaksaanNegeri = "Kejaksaan Negeri",
    PengadilanNegeri = "Pengadilan Negeri",
    KepolisianResor = "Kepolisian Resor",
    KepolisianSektor = "Kepolisian Sektor",
    KepolisianDaerah = "Kepolisian Daerah",
    KepolisianRepublikIndonesia = "Kepolisian Republik Indonesia",
    PengadilanTinggi = "Pengadilan Tinggi",
    MahkamahAgung = "Mahkamah Agung",
    Lainnya = "Lainnya",
}

export enum TingkatPendidikanEnum {
    TidakSekolah = "Tidak Sekolah",
    SDTidakLulus = "SD Tidak Lulus",
    SDAtauSederajat = "SD atau Sederajat",
    SMPAtauSederajat = "SMP atau Sederajat",
    SMAAtauSederajat = "SMA atau Sederajat",
    D1AtauSederajat = "D1 atau Sederajat",
    D2AtauSederajat = "D2 atau Sederajat",
    D3AtauSederajat = "D3 atau Sederajat",
    S1AtauSederajat = "S1 atau Sederajat",
    S2AtauSederajat = "S2 atau Sederajat",
    S3AtauSederajat = "S3 atau Sederajat",
}

export enum TipeKlienEnum {
    Dewasa = "Dewasa",
    Anak = "Anak",
}

export enum UserRoleEnum {
    Pegawai = "Pegawai",
    AdminBapas = "AdminBapas",
    AdminKanwil = "AdminKanwil",
    SuperAdmin = "SuperAdmin",
}

export enum UserStatusAktifEnum {
    Aktif = "Aktif",
    Deaktif = "Deaktif",
}

export enum UserStatusKepegawaianEnum {
    Aktif = "Aktif",
    PindahJabatan = "Pindah Jabatan",
    Pensiun = "Pensiun",
    Lainnya = "Lainnya",
}